services:
  frontend:
    image: matias0512/15dias-frontend:latest
    container_name: 15dias-frontend
    ports:
      - "5173:4173"
    environment:
      VITE_API_URL: https://one5dias-backend.onrender.com/api
